version: '3.7'
services:
  bungeecord:
    image: itzg/bungeecord
    environment:
      BUNGEE_JAR_REVISION: "1"
    ports:
      - 25565:25577
    restart: on-failure
    volumes:
      - ./bungeecord/server:/server
  mc-lobby:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1.5G
    volumes:
      - ./mc-lobby/data:/data
  mc-creative:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1.5G
    volumes:
      - ./mc-creative/data:/data
  mc-survival:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1.5G
    volumes:
      - ./mc-survival/data:/data
